# Generated by Django 4.1.1 on 2022-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0002_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
