# Generated by Django 4.1.1 on 2022-09-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0003_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('coupon', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stripeapp.discount')),
            ],
        ),
    ]
