# Generated by Django 4.1.1 on 2022-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0004_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inclusive', models.BooleanField(default=False)),
                ('percentage', models.FloatField()),
                ('country', models.CharField(max_length=3)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
