# Generated by Django 4.1.1 on 2022-09-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0005_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='rub', max_length=3),
        ),
    ]
